import productImage from "../../../../assets/images/products/product-image.webp";
export const FeaturedProductsData = [
  {
    id: 1,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max",
    ratings: 5.0,
    totalRatings: 120,
    price: 999.0,
    discount: 10,
  },
  {
    id: 2,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max",
    ratings: 2.5,
    totalRatings: 120,
    price: 999.0,
    discount: 50,
  },
  {
    id: 3,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max",
    ratings: 4.2,
    totalRatings: 100,
    price: 59.0,
    discount: null,
  },
  {
    id: 4,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max",
    ratings: 2.5,
    totalRatings: 20,
    price: 999.0,
    discount: null,
  },
  {
    id: 5,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max",
    ratings: 0,
    totalRatings: 20,
    price: 999.0,
    discount: null,
  },
];